# Application version
version: 0.0.1

# The following keys describe the forteframework api skeleton (e.g. where it is installed locally for updates)
api-skeleton:
  # relative path to the API skeleton to be used as a base project of each
  path: "skeleton/forteframework-api-skeleton"

generated:
  # Destination folder for all generated APIs
  path: "build"