<?php

namespace Forte\Worker\Exceptions;

use Forte\Worker\Actions\AbstractAction;
use Forte\Worker\Actions\ActionResult;

/**
 * Class ActionException.
 *
 * @package Forte\Worker\Exceptions
 */
class ActionException extends WorkerException
{
    /**
     * The AbstractAction subclass instance that generated this exception.
     *
     * @var AbstractAction
     */
    protected $action;

    /**
     * A list of ActionException instances, generated by the children actions of the
     * AbstractAction subclass instance wrapped by this ActionException instance.
     *
     * @var array
     */
    protected $childrenFailures = [];

    /**
     * ActionException constructor.
     *
     * @param AbstractAction $action The AbstractAction subclass instance
     * that generated the error.
     * @param string $message The exception message.
     * @param int $code The exception code.
     * @param \Throwable|null $previous The previous error.
     */
    public function __construct(
        AbstractAction $action,
        string $message = "",
        int $code = 0,
        \Throwable $previous = null
    ) {
        parent::__construct($message, $code, $previous);
        $this->action = $action;
    }

    /**
     * Returns the AbstractAction subclass instance
     * that generated this error.
     *
     * @return AbstractAction
     */
    public function getAction(): AbstractAction
    {
        return $this->action;
    }

    /**
     * Return the list of failed children actions.
     *
     * @return array List of failed children actions.
     */
    public function getChildrenFailures(): array
    {
        return $this->childrenFailures;
    }

    /**
     * Set the list of children failures.
     *
     * @param array $childrenFailures List of children
     * failures to be set.
     */
    public function setChildrenFailures(array $childrenFailures): void
    {
        $this->childrenFailures = $childrenFailures;
    }

    /**
     * Add the given ActionException instance to the list of
     * children action failures.
     *
     * @param ActionException $actionException The failure to add.
     */
    public function addChildFailure(ActionException $actionException): void
    {
        $this->childrenFailures[] = $actionException;
    }

    /**
     * Check if some critical failures are found in the failures tree of this
     * ActionException instance.
     *
     * @return bool True if some critical failures were found in the failures
     * tree of this ActionException instance.
     */
    public function hasCriticalFailures(): bool
    {
        return $this->checkForCriticalFailures($this);
    }

    /**
     * Check if some critical failures were found in the failures tree
     * of this ActionException.
     *
     * @return bool True if some critical failures were found in the
     * failures tree of this ActionException.
     */
    public static function checkForCriticalFailures(ActionException $actionException): bool
    {
        $action = $actionException->getAction();
        if ($action->isFatal() || $action->isSuccessRequired()) {
            return true;
        }

        foreach ($actionException->getChildrenFailures() as $actionFailure) {
            if (self::checkForCriticalFailures($actionFailure)) {
                return true;
            }
        }
        return false;
    }
}
